[book]
authors = ["Rishabh"]
description = ""
language = "en"
multilingual = false
src = "src"
title = "The HTML Notes"

[build]
create-missing = false

[rust]
edition = "2018"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/anonymousr007/html-notes"
git-repository-icon = "fa-github"
mathjax-support = true